.projen/deps.json, .projenrc.js, API.md, package.json, src/construct-hub.ts, test/__snapshots__/construct-hub.test.ts.snap, test/construct-hub.test.ts, yarn.lock
In order to allow Construct Hub to leverage 3rd-party libraries, we decided to use v1 instead of v2.
----
=> chore: migrate back to v1

.gitignore, .npmignore, .projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Since construct-hub-webapp currently takes a normal dependency on react-related libraries, bundling it using `bundledDeps` means we will bundle dozens of modules and the tarball size gets to 30MiB.
Instead, take a dev-dependency on it and just copy the `build/` directory from construct-hub-webapp to `website/`, which is then used as the asset.
We can add support in projen to change react-related deps to be dev-deps but this is a good solution for now.
----
=> chore: turn construct-hub-webapp to a dev dependency

.projen/tasks.json, .projenrc.js, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Adds error response config to cloudfront distribution to always return
index.html. This is standard for single page apps deployed on cloudfront
and S3 so that all routing can he handled client side including error
responses.
----
=> fix: cloudfront spa routing

.github/PULL_REQUEST_TEMPLATE.md, .github/pull_request_template.md
```shell
gh repo clone cdklabs/construct-hub foo
Cloning into 'foo'...
remote: Enumerating objects: 490, done.
remote: Counting objects: 100% (490/490), done.
remote: Compressing objects: 100% (277/277), done.
remote: Total 490 (delta 278), reused 362 (delta 179), pack-reused 0
Receiving objects: 100% (490/490), 518.07 KiB | 5.34 MiB/s, done.
Resolving deltas: 100% (278/278), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:
'.github/PULL_REQUEST_TEMPLATE.md'
'.github/pull_request_template.md'
```
=> fix: colliding case-insensitive filesystem filenames

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Adds an http origin to cloudfront to allow accessing files from the
construct-catalog bucket so we can read the jsii assemblies and readme
files for each package.
----
=> feat: add origin for jsii assembly access

API.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/monitoring.test.ts, src/construct-hub.ts, src/monitoring/index.ts, src/monitoring/web-canary.ts, src/webapp/index.ts
Add another dashboard which displays high severity alarms (canaries at this point).
When high severity alarms are added, they will automatically be included in this dashboard. Web canaries will include information about the URL and the name of the canary.
----
=> feat: high severity dashboard

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Adds a behavior to the cloudfront distribution to allow access to the
catalog in awskcdk.io from the webapp. This fixes the broken search
functionality on the frontend.
----
=> fix: proxy path for catalog file to awscdk.io

.projen/deps.json, .projen/tasks.json, .projenrc.js
This [PR](https://github.com/cdklabs/construct-hub/pull/80) locked our CDK version to `1.108.0` in `package.json`. It however did not disable those deps from being upgraded by `ncu` in the upgrade workflow. 
The reason we didn't see cdk upgrades since is actually because the upgrade workflow is [failing](https://github.com/cdklabs/construct-hub/actions/runs/934146327).
```console
warning "construct-hub-webapp > @emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.14.5" has unmet peer dependency "@babel/core@^7.0.0-0".
error An unexpected error occurred: "expected hoisted manifest for \"cdk-watchful#@aws-cdk/aws-cloudwatch#@aws-cdk/core\"".
```
This is the same error we thought would be resolved after [ejecting from the …
=> chore(deps): exclude cdk dependencies from upgrade

src/backend/discovery/discovery.lambda.ts
The check for the presence of versions in the doc was
not correctly handling the case it was trying to handle.
The `Object.keys(v).length === 0` approach fails if
`v` is `null` or `undefined`, which is precisely what
this test was attempting to protect against.
----
=> fix: TypeError when there are no versions in a doc

.gitattributes, .projen/deps.json, .projen/tasks.json, .projenrc.js, package.json
This was an oversight to https://github.com/cdklabs/construct-hub/pull/82 where we excluded cdk dependencies from upgrade.
----
=> chore(deps): exclude constructs from upgrade

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/discovery/discovery.lambda.ts
Changing the batch size used when issuing a request to `couchdb`. This is done to reduce the memory size required during the function execution. Since smaller batch size means lower (average) batch processing time, this PR also reduce the time we require to remain in the Lambda execution in order to request an additional batch.
As mentioned in the code, checking for the time left in the function execution is a best effort, as the distribution of the time it takes to process a package/batch is non uniform, thus we expect the function to time out in some invocations and rely on the downstream idempotency.
----
=> chore(discovery): smaller batch size

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/construct-hub.ts, src/webapp/index.ts
Reverts cdklabs/construct-hub#109.
We are still not really ready to consume data from this backend since a lot of packages are missing.
=> revert: move to dedicated backend

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/ingestion.lambda.ts, src/backend/shared/constants.lambda-shared.ts
Resolves https://github.com/cdklabs/construct-hub/issues/116
Note that the file we'll have will only contain the publish date of the package:
```json
{
"date": "2021-03-03T15:44:28.263Z",
}
```
Since all other information is actually available on the assembly.
An example of how the current file looks like on `awscdk.io`:
```json
{
"name": "aws-cdk-lib",
"scope": "unscoped",
"version": "2.0.0-alpha.6",
"description": "The AWS Cloud Development Kit library",
"keywords": [
"aws",
"cdk"
],
"date": "2021-03-03T15:44:28.263Z",
"links": {
"npm": "https://www.npmjs.com/package/aws-cdk-lib",
"homepage": "https://github.com/aws/aws-cdk",
"repository": "https://github.com/aws/aws-cdk",
"bugs": "https://github.com/aws/aws-cdk/issues"
},
"author": {
"name": "Amazon Web Services",
"url": …
```
=> feat: npm metadata in `metadata.json` file

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/construct-hub.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
Our build is currently failing on the anti-temper check:
```console
diff --git a/src/__tests__/__snapshots__/construct-hub.test.ts.snap b/src/__tests__/__snapshots__/construct-hub.test.ts.snap
index e893473..960c42a 100644
--- a/src/__tests__/__snapshots__/construct-hub.test.ts.snap
+++ b/src/__tests__/__snapshots__/construct-hub.test.ts.snap
@@ -2497,7 +2497,7 @@ function handler(event) {
Object {
"Ref": "AWS::Region",
},
-                "TestConstrubWebAppResponseFunction1F387BCC",
+                "TestConstubWebAppResponseFunction1F387BCC",
],
],
},
```
Im not sure exactly how this happened...looks like this [PR](https://github.com/cdklabs/construct-hub/pull/131) was somehow merged without fully updating from `main`. 
Fixing the snapshots to fix the build while I continue to …
=> chore: fix snapshots

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/monitored-certificate/index.ts
Changes the periodicity of the alarms to 1 day instead of 1 hour, as the
ACM metric is only emitted once a day.
----
=> fix: certificate expiration metrics are on a day scale

API.md, package.json, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.lambda.ts, yarn.lock
Type links are currently broken because of:
1. Links to types in the same package do not sanitize the fqn as the webapp expects it to.
2. Links to types in other packages dont prepend the correct package path (i.e `/packages/...`).
Fixes https://github.com/cdklabs/construct-hub-webapp/issues/128 
----
=> fix: broken type links

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/discovery/constants.lambda-shared.ts, src/backend/discovery/discovery.lambda.ts, src/backend/discovery/index.ts
Emits a metric based on the batches of changes we observe,
not just based on changes concerning relevant packages to
the Construct Hub. This way, the metric should be emitted
almost continuously.
----
=> chore: better monitoring of lag to npmjs.com

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/index.ts
Missing the necessary permission statements to upload the outcome
of transliterating submodules. This adds the necessary statements
to the Bucket policy & function role.
----
=> fix: unable to upload submodules documentation

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/monitored-certificate/certificate-monitor.lambda.ts
The certificate expiry monitor was attempting to directly use the
CloudWatch API, but this failed as permissions were never granted.
This change swicthes to using AWS embedded metrics, so that no
special permissions are needed anymore.
----
=> fix: missing permissions on cloudwatch:PutMetricData

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/construct-hub.ts
The change in VPC layout makes it impossible to update existing deployments,
as the new subnets configuration awkwardly overlaps with the previous one.
This means a new VPC must be created, which is okay, as our VPCs contain no
stateful resources.
----
=> chore: trigger VPC replacement via new logical id

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.lambda.ts
The "file system writable" call is susceptible to a "ENOENT" error in
case the HOME directory has not been created yet. If the environment
variable `$HOME` points to a non-existent directory, attempt to create
it, then proceed to use it as normal if that worked.
----
=> fix: create HOME directory in EFS if it does not exist

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/orchestration/index.ts, src/backend/shared/code-artifact.lambda-shared.ts, src/backend/shared/shell-out.lambda-shared.ts, src/backend/transliterator/index.ts, src/backend/transliterator/transliterator.lambda.ts
If all concurrent Lambda functions share a single $HOME, they end up all
trying to update the same `.npmrc` file. This leads to stale file
descriptor errors (ERRNO -116 / Exit code 140). Instead of sharing the
whole $HOME, configure the NPM cache directory, so that the cache is
shared, but all lambdas keep "their own" home directory.
----
=> fix: do not attempt to share $HOME

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Adds `cache-control: no-cache` header to index.html document to prevent
browsers from caching old versions of the site. Excludes all other
assets so that larger assets, like js and css files, can continued to be
cached locally.
Broke up the `BucketDeployment` into two separate calls as detailed in
[the package docs](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/aws-s3-deployment#prune)
=> fix: add no-cache to index.html

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
This is a revert of https://github.com/cdklabs/construct-hub/pull/268/files since it caused our CloudFront distribution to not be invalidated on deployment. 
Will bring this back after some fixes.
----
=> revert: no cache on index.html

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/deny-list/__snapshots__/deny-list.test.ts.snap, src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.template.json, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/deny-list/deny-list.ts
It is not currently possible to introduce dependencies from consumers of
the DenyList to the S3 Bucket Deployment that creates the deny list,
because this results in a circular dependency when `pruneOnChange` is
enabled on the deny list:
- S3 Bucket Deployment -> S3 Bucket Notification
- S3 Bucket Notification -> Prune Handler
- Prune Handler -> Catalog Builder
- Catalog Builder -> S3 Bucket Deployment
----
=> fix: circular dependency around the deny list

API.md, package.json, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/catalog-builder/catalog-builder.lambda.ts, src/backend/orchestration/index.ts, src/backend/shared/constants.ts, src/backend/shared/language.ts, yarn.lock
Adds Java API reference generation to the backend.
I tested this by deploying to my dev stack, and re-triggering the doc generating step function for cdk8s, and afterwards the Java docs were available successfully at <xxx.cloudfront.net>/data/cdk8s/v1.0.0-beta.41/docs-java.md.
----
=> feat: Java API reference

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/npm-js-follower.lambda.ts
A thrown error in the `httpGet` function within the npm js follower
lambda causes the entire function to fail instead of just logging the
individual package that it is unable to access.
Changed the error handling block to invoke the catch branch of the
promise returned.
----
=> fix: broken error handling in npmjs follower

.github/workflows/auto-approve.yml, .github/workflows/upgrade.yml, .projenrc.js
Use `PROJEN_GITHUB_TOKEN` to align with all projen projects
----
=> chore: update github token

.projenrc.js, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/deny-list/__snapshots__/deny-list.test.ts.snap, src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.template.json, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap, src/backend/catalog-builder/index.ts, src/backend/deny-list/prune-handler.lambda.ts, src/backend/ingestion/index.ts, src/backend/ingestion/ingestion.lambda.ts, src/backend/inventory/canary.lambda.ts, src/backend/inventory/index.ts, src/monitored-certificate/index.ts, src/package-sources/code-artifact.ts, src/package-sources/codeartifact/code-artifact-forwarder.lambda.ts, src/package-sources/npmjs.ts, src/package-sources/npmjs/npm-js-follower.lambda.ts
This disables all automated decoration (i.e: dimensions), which we are
not using anyway, and ensures metrics are flushed out to STDOUT. This is
done by setting an environment variable on Lambda functions that
controls the default behavior of the `aws-embedded-metrics` library.
Locally, this has the effect of correctly emitting the metrics within
the canary lambda function, which stopped working in production a couple
of days/weeks ago for an unknown reason.
----
=> chore: set embedded metrics environment to "Local"

API.md, docs/operator-runbook.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/monitoring/api.ts, src/monitoring/index.ts, src/package-sources/npmjs.ts, src/package-sources/npmjs/constants.lambda-shared.ts, src/package-sources/npmjs/npm-js-follower.lambda.ts
The CouchDB replica for the npmjs.com registry has been rotated,
resulting in resetting the sequence numbers. The NpmJS follower did not
account for this possibility and is hence not registering any changes,
as the marker is now in the distant future from the new sequence.
Added an alarm (low severity) in case no NpmJS changes are registered
for 2 intervals (10 minutes), so we are warned about this in the future.
Additionally, made the NpmJS Follower detect sequence number resets, and
start crawling back from `0` again in this case.
Ref: https://github.blog/changelog/2021-09-08-npm-couchdb-upgrade-will-reset-sequence-number/
----
=> fix: NpmJs not registering new packages

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/inventory/canary.lambda.ts
The inventory function is producing lines that exceed the maximum size
of the CloudWatch logs agent buffer, resulting in dropped metrics as it
catchs it's breath.
Reducing the length of logged lines ensures metrics are properly
produced.
Additionally, stopped outputting unsupported & supported packages, only
outputting the list of missing (i.e: problematic) packages.
Fixes https://github.com/cdklabs/construct-hub-internal/issues/50
----
=> fix: CloudWatch logs buffer saturating in inventory function

.projen/tasks.json, .projenrc.js
Add option ` --no-version-reporting` to command `cdk destroy` in integration tests.
Without this option, command `integ:deny-list:destroy` will change the snapshot used for integration tests. In this case, further test executions will fail.
Fixes #338.
@eladb 
----
=> fix: command `integ:deny-list:destroy` changes snapshot by mistake

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/index.ts
Instead of processing the next page of keys from S3 after all the
current pages have been evaluated, start the child workflow that
processes the next page before handling the key list.
This will make re-ingestion traverse the bucket significantly faster,
and greatly improve the downstream concurrency.
----
=> chore: improve velocity of re-ingest workflow

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/ingestion.lambda.ts
CodeArtifact publishing is a best-effort attempt, and should not
normally be necessary. Changes the code path so that:
1. It is not attempted if there is `publishConfig` in the package.json
file, as this would override the configrued registry;
2. Failures are simpluy logged and ignored
----
=> fix(ingestion): CA publish failures cause ingestion failures

.projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, src/JSONStream.d.ts, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/couch-changes.lambda-shared.ts, yarn.lock
Instead of limiting the response size, leverage JSONStream to parse the
JSON objects in a streaming fashion. This simplifies the code for
handling the HTTP response payloads.
----
=> chore: use JSONStream to be safe with large responses

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/canary/index.ts, src/package-sources/npmjs/canary/npmjs-package-canary.lambda.ts
The `.end()` call is necessary when using `https.request()`, but was
missing, which eventually resulted in the connection being aborted by
the service or firewall, which triggered an un-caught `ECONNRESET`
error.
This caused the `node` VM to abort, and ultimately prevented the updated
state object to be written to S3 in the `finally` clause.
---
Note - the `https.get` method (used in `getJSON`) does NOT need `.end()`
to be called, as that particular method does not allow a request payload
to be written.
----
=> fix: npmjs package canary failed on HEAD requests

.projenrc.js, API.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/construct-hub.ts, src/spdx-license.ts
Adding the CDDL, EPL, ISC and MPL-2.0 license families to the Hub's
default license allow-list, following legal review of their terms.
----
=> chore: add new licenses to the default allow-list

API.md, README.md, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/devapp/dev-stack.ts, src/__tests__/webapp/config.test.ts, src/construct-hub.ts, src/index.ts, src/webapp/config.ts, src/webapp/index.ts
Allow configuring browse categories. Each category has a `title` and a `url`. Categories are rendered into the `config.json` file that the frontend consumes in order to render the home page.
Related cdklabs/construct-hub-webapp#682
----
=> feat: browse categories

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/index.ts
Adding bucket versioning to this makes it easier to debug when the configuration was updated / determining how long some package tag has been in effect etc.
----
=> chore: add bucket versioning to configuration bucket

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/ingestion/ingestion.lambda.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/ingestion.lambda.ts
As a follow up to #567, delete additional large fields from `assembly.json` that are not used by the client. Namely: `readme` and `dependencyClosure`.
Related to cdklabs/construct-hub-webapp#691
----
=> feat: reduce assembly size even more

README.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs.ts
We initially triggered low severity alarms to gain confidence in the alarm without creating too much noise. 
Now, we apply the correct severity for this alarm as it indicates a either a malfunctioning pipeline or CloudFront distribution. 
----
=> feat: package canary triggers high severity alarm

src/__tests__/__snapshots__/_limited-internet-access.test.ts.snap, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/_limited-internet-access.ts
We have provisions to cause the `CfnPrefixList` resource to be replaced
when its allow-list changes (the CIDR range capacity of `CfnPrefixList`
cannot be updated once it's deployed).
Due to how SecurityGroup in-/e-gress rules are managed by CDK, this
means the SecurityGroup that uses a `CfnPrefixList` will first be
updated by CloudFormation to add the new `CfnPrefixList` reference, and
during `CLEAN_UP`, the outdated list will be removed. This has the
potential of exceeding SecurityGroup rule count limits relatively
easily.
In order to address this problem, this causes the SecurityGroup to be
replaced whenever the `CfnPrefixList` gets replaced. As the
SecurityGroups are only used by Fargate task definitions, this will
cause a new revision of the task definition to be created, and will …
=> fix: unable to deploy updated IP allow-lists

API.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/devapp/dev-stack.ts, src/backend/ingestion/index.ts, src/construct-hub.ts, src/temp-file.ts, src/webapp/config.ts, src/webapp/index.ts
This pull request adds a new prop to the `ConstructHub` class to support a preload.js script on the webapp. This addition will allow us to remove our analytics script from our npm package, as well as allow construct hub instances to have their own javascript run before the webapp is served (if needed)
----
=> feat: support preloadScript

.github/workflows/build.yml, .github/workflows/upgrade-main.yml, .projen/tasks.json, package.json, yarn.lock
The upgrade PR is failing because the packaging tasks have changed, and can no longer be executed in the upgrade workflow. 
https://github.com/cdklabs/construct-hub/runs/4659375512?check_suite_focus=true
```console
package-all » package:js | jsii_version=$(node -p "JSON.parse(fs.readFileSync('.jsii')).jsiiVersion.split(' ')[0]")
internal/fs/utils.js:312
throw err;
^
Error: ENOENT: no such file or directory, open '.jsii'
at Object.openSync (fs.js:498:3)
at Object.readFileSync (fs.js:394:
```
This will be resolved after this upgrade because we won't run these commands anymore.
----
=> chore(deps): upgrade dependencies

README.md
=> fix(docs): public Construct Hub is GA, not Dev Preview

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/index.ts
The daily reprocessing job enqueues 60,000 packages all at once
every day to be reprocessed. This completely overloads the ECS
cluster, with the following consequences:
* On-demand work (like the NPM follower) suffers from being drowned
out by 60k work items, and our latency on processing package updates
spikes to 30 minutes or sometimes even more than an hour, triggering
alarms.
* Since there is no backpressure, we keep on hammering the ECS cluster
trying to start tasks, retrying until it succeeds. Eventually this
sometimes still fails and messages end up in the DLQ, triggering
alarms and requiring human intervention.
This PR mellows the reprocessing driver out a bit, by not having it fill
the worker queue as fast as it can: instead, we will feed the system
work at about the pace we know …
=> fix: daily reprocess job interferes with NPM follower

docs/application-overview.md
The severity of the alarm was changed in https://github.com/cdklabs/construct-hub/pull/597, but wasn't updated here.
----
=> docs: package canary triggers high severity alarm

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/inventory/canary.lambda.ts
Our package canary was reporting most packages as unknown or missing because of a bug where we were matching against keys incorrectly. This PR fixes the bug, and cleans up the rest of the canary code to properly handle the fact that we are generating both json and markdown documents, but do not want to double count the number of identified packages (nor count either type of file as "unknown").
----
=> fix: inventory canary reporting packages as unknown

docs/operator-runbook.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/index.ts
Fixes #759
In some cases, we noticed messages appearing in our Orchestration DLQ with the message "Forbidden: null". This message suggests a permission error. We identified the most likely cause was the transliterator ECS task did not have the correct permission to read "uninstallable" object markers that we assign to packages that fail to install with `npm install`. We were currently granting write and delete permissions, but not read permissions.
I would add a unit test for our transliterator to prevent a regression for this path in the code, but the cause of this bug is a permission error so it wouldn't really be caught by any test we write unless it was a full-on integration test, which is a bit out of the scope of this PR. 
----
*By submitting this pull request, I confirm that my …
=> fix: transliterator fails when reprocessing an uninstallable package

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/orchestration/redrive-state-machine.lambda.ts
Removes the docGen field from messages before redriving to the
orchestration SFN input. Previously, these could become too long and
would cause redriving to error with "Container Overrides length must be
at most..."
Notably, when starting to generate Go documentation, some packages
failed because the rosetta tablet had been generated before jsii-rosetta
supported Go. These failures were sent to the DLQ with the error
message "The following snippet was not found in any of the loaded
tablets: SNIPPET", where the snippet could be understandably quite long.
----
=> fix: remove error messages from redriven messages

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs.ts
Right now, the NPM/NoChanges alarm kicks in after 10 minutes.
However, NPM periodically has changes in which it's pretty unhappy,
will throttle us heavily until the Lambda finally times out (and
subsequently, saw no changes). This cuts us nonactionable tickets
(since we don't control NPM) and is generally just annoying.
Increase the alarm sensitivy to an hour without changes.
----
=> chore: reduce aggressiveness of NoChanges alarm

.projenrc.js
CDK V2 has default support for some of the features and the  feature flags have been removed. Removing the unsupported featur flags
----
=> fix: remove unsupported feature flags from dev app

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs.ts
The npmjs follower frequently fails due to issues with the npmjs
replica. In these instances there is no action item other than to wait
for the replica to recover. Lowering the severity of the alarm.
----
=> chore(npmjs): follower alarm should be low severity

API.md, docs/operator-runbook.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/catalog-builder/index.ts, src/monitoring/api.ts, src/monitoring/index.ts, src/package-sources/npmjs.ts, src/package-sources/npmjs/canary/constants.ts, src/package-sources/npmjs/canary/index.ts, src/package-sources/npmjs/canary/npmjs-package-canary.lambda.ts
In the last few weeks we have regularly observed a large gap between the
npmjs replica database (replicate.npmjs.com/registry) and the registry's
primary endpoint (registry.npmjs.org). When this happens, the SLA breach
alarm triggers despite ConstructHub cannot possible have indexed new
packages (as these are not visible on the replica just yet).
To reduce inactionnable alarms, this adds a process to measure the lag
that is observed between the primary and replica, and suppresses the
SLA alarm in case the delta is found to be too large to allow the SLA to
be met.
Additionally, the SLA alarm triggering is not necessarily indicative of
an operational issue with ConstructHub, and will not be immediately
customer-affecting. As a consequence, it was downgraded from high- to
low-severity.
---- …
=> chore: mitigate alarm verbosity

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs.ts, src/package-sources/npmjs/canary/constants.ts, src/package-sources/npmjs/canary/index.ts, src/package-sources/npmjs/canary/npmjs-package-canary.lambda.ts
Sometimes, the NpmJS canary errors because replicate.npmjs.com is down, causing an alarm to be triggered. There's no use failing and alarming since there's nothing that that can be done by the operator. So this PR catches the error, and opts to simply not report the NPM replica lag metric when it's unavailable.
The Npmjs/Canary/SLA-Breached alarm, which depends on this metric to determine if replicate.npmjs.com is down (and disable the alarm accordingly), will now fill in values based on what the last reported lag-time metric was, instead of filling in empty values with 0.
----
=> fix(npmjs): canary alarms when replicate.npmjs.com is down

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs.ts, src/package-sources/npmjs/canary/constants.ts, src/package-sources/npmjs/canary/index.ts, src/package-sources/npmjs/canary/npmjs-package-canary.lambda.ts
We are seeing semi-frequent occurrences of npm servers being impaired
and returning HTTP Gateway errors (HTTP 502, HTTP 504). There is nothing
we can do but wait for these to resolve, so we should not be failing and
alarming unless the situation persists for an extended amount of time.
This change catches HTTP errors and "ignores" HTTP 502 and HTTP 504
errors, while emitting a metric to reflect those errors being
encountered. A new low-severity alarm will fire if we continue to see
HTTP 502 and HTTP 504 errors on every single run for more than 60
minutes.
I chose not to apply a back-off & retry policy as those issues are
usually caused by servers being overloaded and the best strategy here
is to let these servers cool off, not pile up more load on them.
----
*By submitting this pull …
=> fix: NpmJs source canary fails when npm servers are impaired

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/canary/npmjs-package-canary.lambda.ts
The canary currently fails when npm returns a status of `503 Service
Unavailable`, which should be handled the same as other known 500 cases.
This causes the metric to correctly be emitted and supress other alarms
due to service outage.
fixes: #916
----
=> fix: canary fails on npm returning 503

.projen/tasks.json, .projenrc.js, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
The AmazonLinux 2 image does not come with a GLibc that
is compatible with node 18 from nodesource.
----
=> fix: use node16 in ECR image

.github/workflows/update-vpc-acl-allow-lists.yml, .projenrc.js
Reverts the update to our ACL list update gh action to use v4 of the create-pull-request action as it breaks when using a personal access token. Apparently we can't grant the permissions needed to request reviews from teams using personal access tokens and can only do so using a github app.
Other actions built into projen use v3 of this action anyway so less variance feels better.
reverts: 4042a227ac7893aeb1891268ae08de365e08f8f3, b4fb2cddc4c5151b87a03039fb82b95338954642
=> chore: revert update create-pull-request to v4

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/backend/transliterator/transliterator.ecstask.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.ecstask.ts
In the previous fix PR, I missed that `languages` can be absent which is implied to mean "all languages", which caused underestimation of response size.
Fix that.
----
=> fix: misinterpreted what it means to have no `languages`

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/ingestion/ingestion.lambda.test.ts, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/ingestion.lambda.ts
If the ingestion function receives two records for the same package, it will try to start the execution of the step function twice with the same name but different inputs, because the version ID returned by S3 is part of the input. In this case, the SDK will throw an [`ExecutionAlreadyExists`][1] error.
Prevent this by accumulating the packages that were seen in a set. Only unseen packages are processed.
[1]: https://docs.aws.amazon.com/step-functions/latest/apireference/API_StartExecution.html
----
=> fix: ingestion function tries to execute more than once if the package name and version are duplicated

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ecs-task-monitor/index.ts
The ECS task monitor lambda fails on the following error:
```
AccessDeniedException: User: arn:aws:sts::573688003310:assumed-role/<...> is not authorized to perform: ecs:ListTasks on resource: * because no identity-based policy allows the ecs:ListTasks action
```
This is because the `ecs:ListTasks` action may only be scoped by `container-instance`, and we're listing across all container instances in the main cluster, so the `Resource` being authorized for is `*`, and the `ecs:cluster` condition provides the necessary scoping down.
----
=> fix: incorrect ecs:ListTasks permission

.projenrc.ts, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/index.ts, src/backend/transliterator/transliterator.ts
We never set the `--max-old-space-size` option when running the node process inside the transliterator task. I guess this was missed during our migration from Lambda to ECS. 
----
=> fix: transliterator task isn't using all available memory

.projen/tasks.json, projenrc/bundle-javascript-for-ecs.exec.ts, projenrc/magic-ecs.ts, projenrc/magic-lambda.ts, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap
Replaces `node16` targets in projen tasks with `node18`.
----
=> chore: upgrade targets to node18

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Fixes #1351 by making use of the [viewer protocol policy](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-viewerprotocolpolicy) of Cloudfront distributions.
* Enforces https redirects for clients that do not support HSTS header
* Applied to all behaviors of Cloudfront distribution
----
=> fix: Add redirect to https viewer protocol policy

docs/operator-runbook.md, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/feed-builder/index.ts, src/construct-hub.ts
The feed builder lambda was timing out and consistently failing causing the atom feed to not be updated.
After investigation, it was determined the default memory, 128MB, was insufficient for the lambda to correctly execute. This PR increases the memory to 1024MB, a number verified by dev testing, and adding an alarm such that future issues will be flagged.
Below you can see the metrics from the lambda function before and after increasing the memory allocation, approximately 21:45UTC.
Note that when the issue was resolved the invocations, throttles and events spike, then return to a low steady state. I believe this is due to the long backlog of work the lambda had to work through as it hasn't run correctly in ~seven months.
This fixes #1238.
----
*By submitting this pull request, I …
=> fix: Feed builder lambda times out

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs.ts
We are observing that upon resolution of npmjs replica lag, the `SLA-Breached` alarm triggers during the period of time where the application consumes the updates from the backlog. The alarm is self resolving as there is no issue with the backend.
Update the evaluation period from 2 (10 minutes) to 4 (20 minutes) to allow for the system to catch up before reporting an alarm.
----
=> fix: Updating SLA-Breached evaluation periods

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/index.ts, src/package-sources/npmjs.ts
We are observing that the `DLQNotEmpty` alarms for both staging and ingestion are being regularly triggered. They auto-resolve after a single data point and do not leave meaningful info.
Update the evaluation period from 1 (5 minutes) to 2 (10 minutes) to allow the issue to auto-resolve without alarming.
_By submitting this pull request, I confirm that my contribution is made under the terms of the Apache-2.0 license_
This was original authored as #1401, but needed the snapshots updated.
=> fix: Update DLQNotEmpty evaluationPeriods

.projen/deps.json, .projenrc.ts, package.json, yarn.lock
Related to #1379, we need to upgrade `jsii`. This PR upgrades from `5.1.x` to `5.2.x`. We still need to make further upgrades, but this is the first increment.
----
=> chore: Upgrade jsii to 5.2.x

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/shared/constants.ts, src/backend/transliterator/transliterator.ecstask.ts
Without this, orchestration will always fail loudly.
A `TransliterationError` is emitted by `jsii-docgen` when transliteration by `jsii-rosetta` failed.
This always implies that all (sub-)modules for the given language will fail, since the transliteration step is not submodule specific.
----
=> fix(orchestration): handle new jsii-docgen transliteration error

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.ecstask.ts
In the observed logs, the slow down error return by S3 apparently do not contain the human friendly names.
According to the S3 docs [1], a `503` error always indicates a slow down request.
This PR adds a few more checks to detect retryable errors more reliably.
Also increases the wait time between retry requests slightly to make slow downs less likely.
[1] https://repost.aws/knowledge-center/http-5xx-errors-s3
----
=> fix(transliterator): s3 uploads are not retried when slowed-down

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/feed-builder/update-feed.lambda.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/feed-builder/update-feed.lambda.ts
In #1451 the update-feed function was migrated to SDK v3. For the migration the error handling needed to be adapted to SDK v3. With SDK v2 we checked for a `404` error status to conclude that no release notes are available. SDK v3 does not use http error codes, so we needed to convert to error names/types. Initially this was incompletely changed to only check for a `NotFound` error. However it also needs to check for `NoSuchKey` error. 
This has been fixed and the testcase updated.
----
=> fix(feed-builder): updating feed fails when package has no release notes

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/catalog-builder/catalog-builder.lambda.ts
In #1441 we upgraded the SDK to v3. During this upgrade we replaced the deprecated InvokeAsyncCommand with InvokeCommand. It was missed that the default invocation type for this command is `RequestResponse`, when it needs to be `Event`. This caused the catalog-builder function to await the completion of the feed-builder function.
----
=> fix(catalog-builder): average execution time is 100x slower than previously

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ecs-task-monitor/monitor.lambda.ts
Refactor the ecs-task-monitor lambda functions to use AWS SDK v3.
----
=> fix(ecs-task-monitor): upgrade to AWS SDK v3

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/deny-list/mocks/trigger.prune-test.lambda.ts, src/__tests__/backend/license-list/client.lambda.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap, src/backend/license-list/client.lambda-shared.ts, test/integ.deny-list.ts.snapshot/DenyListInteg.assets.json, test/integ.deny-list.ts.snapshot/DenyListInteg.template.json, test/integ.deny-list.ts.snapshot/manifest.json, test/integ.deny-list.ts.snapshot/tree.json
Refactor the license-list client to use AWS SDK v3. Tests updated accordingly.
Also fixes a mock function for the deny-list integ test to use SDK v3.
----
=> fix(license-list): upgrade to AWS SDK v3

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/version-tracker/version-tracker.lambda.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/version-tracker/version-tracker.lambda.ts
Refactor the version-tracker function to use AWS SDK v3. Tests updated accordingly.
----
=> fix(version-tracker): upgrade to AWS SDK v3

docs/errors-encountered.md
Updates the runbook with updated details on Running Out of File Descriptors error.
----
=> chore(runbook): updated section about file descriptor error

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/index.ts
When MaxKeys is 1000 (default), sometimes the `ReprocessIngestionWorkflow` fails due to the `DataLimitExceeded` state error. The limit is 256KB according to [Step Functions service quotas](https://docs.aws.amazon.com/step-functions/latest/dg/service-quotas.html) and cannot be reconfigured. 
Reducing MaxKeys can bring us below the service quota, but increases workflow running time. This change runs the workflow at `maxKeys: 1000`, and reruns it with MaxKeys decremented by 100 if the workflow fails on the `DataLimitExceeded` state error, with a floor of `maxKeys: 100`.
----
=> fix: decrement MaxKeys from 1000 by steps of 100 when encountering DataLimitExceeded

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/index.ts
Adds lambda insights to the web app s3 deployment lambda, so that we can track memory usage over time and other metrics.
Testing includes updates to the snapshots and I deployed Construct Hub to my personal account and confirmed that lambda insights was turned on:
----
=> feat: lambda insights on web app deployment lambda

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/couch-changes.lambda-shared.ts
the npm follower now makes a GET request for every package it finds. occasionally, that results in a 404 error. we shouldn't fail the entire lambda on these, and instead log and move on.
----
=> fix: npm follower lambda fails on 404 errors

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/npm-js-follower.lambda.ts
=> fix: resetting the npm follower cache deletes all known versions

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/couch-changes.lambda-shared.ts, src/package-sources/npmjs/npm-js-follower.lambda.ts
The follower has a mechanism to stop processing when it reaches the end of the replication log. It determines this by looking at the number of changes received and if that's zero, we must be up-to-date.
Due to a code bug, this check was only considering actionable changes. I.e. changes that are not deleted and have metadata. A lot of the changes at the beginning of the log are not actionable. It is therefore extremely common that a batch does not contain any actionable changes. Which than leads the follower to incorrectly believe it has caught up and bail out of processing.
Instead we use the total number of changes as a metric to decide if we are at the end of the log.
----
=> fix: follower processes only 100 changes every 5min

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend-dashboard.ts
=> fix: split state machine graph widgets into success and failure graphs
