cdklabs/construct-hub

.github/workflows/build.yml, .github/workflows/projenupgrade.yml, .github/workflows/release.yml, .projen/deps.json, .projen/tasks.json, .projenrc.js, package.json, src/construct-hub.ts, src/dummy/handler.ts, src/dummy/index.ts, src/monitoring/index.ts, test/devapp/__snapshots__/snapshot.test.ts.snap, yarn.lock
Create a monitoring construct that uses cdk-watchful to automatically generate a dashboard for any resources
within the app.
Related to #8
----
=> feat: initial monitoring construct

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/construct-hub.test.ts
Add a few snapshot tests as a baseline for regression testing.
----
=> chore: add some snapshots as a baseline

.projen/deps.json, package.json, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/transliterator.lambda.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.lambda.ts, yarn.lock
The bug fixed by #74 subsisted due to a leftover use of `decodeURI`, which
does not work hard enough for this problem. The test failed to catch that due
to an incorrect expectation.
----
=> chore: fix broken test

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/ingestion/ingestion.lambda.ts
The correct content-type for json files is `application/json`. 
----
=> fix: wrong content type for json files

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
=> chore: fix snapshots

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/backend/discovery/discovery.lambda.ts
This [PR](https://github.com/cdklabs/construct-hub/pull/178) was accidentally merged with an unintended change to the discovery marker file. Reverting to original value.
----
=> chore: revert discovery marker

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/orchestration/index.ts
I forgot to grant permissions to read the Bucket and start
the State Machines executions... Oops.
----
=> fix: missing permissions for ReprocessAll function

.projenrc.js, package.json
=> fix: typo in package.json description

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/npm-js-follower.lambda.ts
=> chore: add awscdk as a valid keyword

.projen/tasks.json, .projenrc.js, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/deny-list/__snapshots__/deny-list.test.ts.snap, src/__tests__/backend/deny-list/integ/deny-list.integ.cdkout/TestDenyList.template.json, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap, src/backend/inventory/canary.lambda.ts
Added more logging around the Canary function's metric emission, and an
explicit metric logger flush operation, hoping this will solve our issue.
----
=> chore: further investigate metrics emission problem

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/webapp/response-function/response-function.ts
This reverts commit 6e374efe479cea0ff2f7d4d30127c43dff65a38e. It caused the website to stop returning responses, with the error message:
```
503 ERROR
The request could not be satisfied.
The CloudFront function associated with the CloudFront distribution is invalid or could not run. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 
```
----
=> chore: revert "chore: clean up CloudFront returned headers (#398)"

API.md, README.md, src/__tests__/webapp/config.test.ts, src/construct-hub.ts, src/index.ts, src/webapp/config.ts, src/webapp/index.ts
=> feat: configure web app feature flags

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/s3/vpc-endpoint-bucket.ts
=> fix: support grantDelete on S3 VPC Endpoint proxy

.github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/package-removal.yml, .github/ISSUE_TEMPLATE/website-bug.yml
=> chore: add GitHub issue forms

.github/ISSUE_TEMPLATE/package-removal.yml
"description" field is required
----
=> fix: broken issue template

.projen/tasks.json, .projenrc.js, API.md, package.json, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/backend/transliterator/transliterator.ecstask.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/inventory/canary.lambda.ts, src/backend/shared/constants.ts, src/backend/transliterator/transliterator.ecstask.ts, yarn.lock
Revert change in api url generation and version of jsii-docgen.
This reverts commit 9dc98372469f9b1803618de038f2956caf3397ad.
----
=> chore: "fix: improve API reference URLs (#720)"

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/construct-hub.ts
=> fix: appRegistry default is not applied

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/catalog-builder/catalog-builder.lambda.ts, src/backend/shared/constants.ts, src/backend/shared/language.ts
Adds logic to generate go language documentation for packages that
support it.
Fixes https://github.com/cdklabs/construct-hub/issues/282
----
=> feat: go documentation support

src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap, src/__tests__/package-sources/codeartifact/code-artifact-forwarder.lambda.test.ts, src/package-sources/codeartifact/code-artifact-forwarder.lambda.ts
=> fix(codeartifact): InvalidParameterValue SQS error after publishing construct

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/shared/constants.ts, src/webapp/badge-redirect-function/index.ts, src/webapp/badge-redirect-function/redirect-function.ts, src/webapp/index.ts, src/webapp/response-function/response-function.ts
See https://github.com/cdklabs/construct-hub-webapp/pull/997 for more details
----
=> feat: github badges (backend)

package.json, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, yarn.lock
=> fix: bump jsii-docgen to deal with install bug

.projenrc.js, package.json, yarn.lock
=> chore: address dependabot security alert for nth-check

.projenrc.js, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/orchestration/index.ts, src/backend/transliterator/transliterator.ecs-entrypoint.ts, src/backend/transliterator/transliterator.ecstask.ts
fix: ecs task not actually aborting when step functions has abandoned the task
chore: reduce heartbeat amount
chore: log incoming event in parseable format
----
=> chore(backend/transliterator): minor ops improvements

.projenrc.js, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.ecs-entrypoint.ts
=> chore: dump heap statistics when sending heartbeat

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/orchestration/redrive-state-machine.lambda.ts
Failure to do so may result in an excessively large input that will later choke ECS.
----
=> chore: trim down SFN redrive input

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/upgrade-main.yml, .projen/deps.json, .projenrc.js, package.json, yarn.lock
=> chore: upgrade some dependencies

API.md, README.md
=> docs: clarify that consuming all of NPM is a bad idea

package.json, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/construct-hub.ts, yarn.lock
=> chore: upgrade jsii-docgen again

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/catalog-builder/catalog-builder.lambda.ts
=> fix: consume tar-stream entry stream to unblock processing

.github/ISSUE_TEMPLATE/package-removal.yml, .github/ISSUE_TEMPLATE/verified-partner.yml
=> chore: add package verification form

projenrc/magic-ecs.ts, src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap
=> fix(ecs): enable source maps for better debugging

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/backend/transliterator/__snapshots__/index.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/transliterator/transliterator.ecstask.ts
and some other tweaks not not be throttled by s3
----
=> fix(transliterator): fix semaphore not limiting requests

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/__tests__/package-sources/__snapshots__/code-artifact.test.ts.snap, src/__tests__/package-sources/codeartifact/code-artifact-forwarder.lambda.test.ts, src/__tests__/package-sources/npmjs/stage-and-notify.lambda.test.ts, src/package-sources/codeartifact/code-artifact-forwarder.lambda.ts, src/package-sources/npmjs/canary/npmjs-package-canary.lambda.ts, src/package-sources/npmjs/npm-js-follower.lambda.ts, src/package-sources/npmjs/stage-and-notify.lambda.ts
Refactor the package-source lambda functions to use AWS SDK v3. Tests updated accordingly.
----
=> fix(package-sources): upgrade to AWS SDK v3

src/__tests__/backend/release-notes/generate-release-notes.lambda.test.ts, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/backend/release-notes/generate-release-notes.lambda.ts, src/backend/release-notes/get-messages-from-worker-queue.lambda.ts, src/backend/release-notes/release-notes-trigger.lambda.ts
Refactor various release-notes lambda functions to use AWS SDK v3. Tests updated accordingly.
----
=> fix(release-notes): upgrade to AWS SDK v3

README.md
=> feat: state machine ReprocessDocumentationPerPackage's behavior documented

docs/operator-runbook.md
=> chore: fix formatting in operator-runbook.md

docs/operator-runbook.md
=> chore: add instructions on contacting NPM to runbook

docs/errors-encountered.md
=> chore: add SIGKILL to errors-encountered.md

docs/operator-runbook.md
=> chore: correct links for npm package canary

src/__tests__/__snapshots__/construct-hub.test.ts.snap, src/__tests__/devapp/__snapshots__/snapshot.test.ts.snap, src/package-sources/npmjs/couch-changes.lambda-shared.ts, src/package-sources/npmjs/npm-js-follower.lambda.ts
Follow up to #1689 that did not do this correctly.
----
=> fix: npm follower ignores 404 errors correctly
